import { useState } from 'react'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Featured from '../components/Featured'
import Add from '../components/Add'
import AddButton from '../components/AddButton'
import ProductsList from '../components/ProductsList'
import { urlBase } from '../config/requestMethod'

export default function Home({ burgerList, admin }) {
    const [close, setClose] = useState(true)
    console.log(close);
    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Featured />
            {admin && <AddButton setClose={setClose} />}
            <ProductsList burgerList={burgerList} />
            {!close && <Add setClose={setClose} />}
        </div>
    )
}

export const getServerSideProps = async (ctx) => {
    const myCookie = ctx.req?.cookies || "";
    let admin = false;

    if (myCookie.token === process.env.TOKEN) {
        admin = true;
    }
    const res = await urlBase.get("products");
    return {
        props: {
            burgerList: res.data,
            admin
        }
    }
}