import Head from 'next/head'
import Featured from '../components/Featured'
import styles from '../styles/Home.module.css'
import ProductsList from '../components/ProductsList'
import axios from 'axios'

export default function Home({ burgerList }) {
    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Featured />
            <ProductsList burgerList={burgerList} />
        </div>
    )
}

export const getServerSideProps = async () => {
    const res = await axios.get("http://localhost:3000/api/products");
    return {
        props: {
            burgerList: res.data
        }
    }
}